name: Release S-UI

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - '.github/workflows/release.yml'
      - 'frontend/**'
      - '**.sh'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          mv frontend/dist web/html
          rm -fr frontend

      - name: Build s-ui
        run: |
          go mod download
          gopath=$(go env GOPATH)
          router_file=$(find "$gopath/pkg/mod/github.com/sagernet" -name "router_freebsd.go" | head -n 1)
          if [ -n "$router_file" ] && [ -f "$router_file" ]; then
            echo "Found tailscale freebsd router file at: $router_file"
            # 必须同时给父目录和文件加上可写权限，否则 sed 无法在同级目录下创建临时文件
            chmod +w "$(dirname "$router_file")" "$router_file"
            sed -i 's|"github.com/sagernet/wireguard-go/tun"|// "github.com/sagernet/wireguard-go/tun"|g' "$router_file"
            echo "Successfully patched tailscale FreeBSD unused import."
          fi
          
          export CGO_ENABLED=0
          export GOOS=freebsd
          export GOARCH=amd64
          go build -ldflags "-w -s" -tags "with_quic,with_grpc,with_utls,with_acme,with_gvisor" -o sui main.go
          
          mkdir s-ui
          cp sui s-ui/
          cp s-ui.sh s-ui/

      - name: Package
        run: tar -zcvf s-ui-freebsd-amd64.tar.gz s-ui

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: s-ui-freebsd-amd64
          path: ./s-ui-freebsd-amd64.tar.gz
          retention-days: 30

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        if: |
          (github.event_name == 'release' && github.event.action == 'published') ||
          (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: s-ui-freebsd-amd64.tar.gz
          asset_name: s-ui-freebsd-amd64.tar.gz
          prerelease: true
          overwrite: true
